[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
OptimizationParameters = "7e4d55e1-29a6-451b-8e82-71170a6dda04"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SIRENOpt = "d5b4a993-64e1-4ef8-bb58-429dd9f6ab21"

[sources]
AgnosticStorageDynamics = {rev = "master", url = "https://github.com/sandialabs/AgnosticStorageDynamics.jl.git"}
Desal = {rev = "master", url = "https://github.com/sandialabs/Desal.jl.git"}
DieselGen = {rev = "master", url = "https://github.com/sandialabs/DieselGen.jl.git"}
DimensionfulAngles = {rev = "main", url = "https://github.com/JuliaOceanWaves/DimensionfulAngles.jl.git"}
GeneratorSE = {rev = "master", url = "https://github.com/sandialabs/GeneratorSE.jl.git"}
H2Gen = {rev = "master", url = "https://github.com/sandialabs/H2Gen.jl.git"}
Hydrodynamics = {rev = "main", url = "https://github.com/JuliaOceanWaves/Hydrodynamics.jl.git"}
Mooring = {rev = "main", url = "https://github.com/CMOE-TUDelft/Mooring.jl.git"}
OptimizationParameters = {rev = "master", url = "https://github.com/byuflowlab/OptimizationParameters.jl.git"}
PVlib = {rev = "main", url = "https://github.com/sandialabs/PVlib.jl.git"}
PowerConverterDynamics = {rev = "master", url = "https://github.com/sandialabs/PowerConverterDynamics.jl.git"}
SIRENOpt = {path = ".."}
UnsteadyKineticRotorDynamics = {rev = "master", url = "https://github.com/sandialabs/UnsteadyKineticRotorDynamics.jl.git"}
WaveSpectra = {rev = "main", url = "https://github.com/JuliaOceanWaves/WaveSpectra.jl.git"}

[compat]
Documenter = "1"
Literate = "2"
OptimizationParameters = "0.1"
Plots = "1"
SIRENOpt = "0.1"

[extras]
AgnosticStorageDynamics = "32e03c9e-1ca1-4f94-998d-0c16334532c1"
Desal = "c10c95ac-9782-4ee4-9116-e2afe774bfc7"
DieselGen = "bc32595d-1e16-433f-a342-06d36c30239a"
DimensionfulAngles = "2d4b8d7a-02d9-40f9-9abe-9c695b77de0d"
GeneratorSE = "5123460e-7fba-4c4e-a1c3-84f556528963"
H2Gen = "723521b7-fb78-4ee2-baa8-3c80454e07bc"
Hydrodynamics = "63c6a582-8669-4cdf-95d2-d1c53f837950"
Mooring = "54d656fe-1954-4949-b509-86ef6fd939c8"
PVlib = "7b90ca13-13a1-463a-b450-7b420c616eff"
PowerConverterDynamics = "aefe4765-8842-4c6b-bc21-1d476c04fa12"
UnsteadyKineticRotorDynamics = "51f0175b-34ed-4c43-bdd0-6e07bed75fb5"
WaveSpectra = "9da5bd80-4f3d-48a2-a37e-447dff2ef7bc"
